# 数据分析

In [2]:
import numpy as np
import pandas as pd
import re
df = pd.read_csv(r'rent_source_合并.csv', header= 0,
                 names =['title','location','price','url','source'] )

In [3]:
df[:5]

,title,location,price,url,source
0,木樨园 整租·南三环中路69号 1室1厅 南,南三环中路69号,4000,https://bj.lianjia.com/zufang/BJ23556994338301...,lj
1,芍药居 整租·芍药居北里 2室1厅 东,芍药居北里,6000,https://bj.lianjia.com/zufang/BJ23556927120463...,lj
2,定慧寺 整租·恩济庄82号院 1室0厅 北,恩济庄82号院,3500,https://bj.lianjia.com/zufang/BJ23556403944457...,lj
3,通州北苑 整租·长城国际 1室0厅 西,长城国际,3600,https://bj.lianjia.com/zufang/BJ23555436027274...,lj
4,通州北苑 整租·长城国际 2室1厅 东,长城国际,3600,https://bj.lianjia.com/zufang/BJ23555381849953...,lj

In [4]:
#新增一列，作为区域地址
df['address'] = 'add'
for index in range(len(df)):
    df.loc[index,'address'] = re.findall('(.*?) .*',df.loc[index,'title'])

In [5]:
df[:10]

,title,location,price,url,source,address
0,木樨园 整租·南三环中路69号 1室1厅 南,南三环中路69号,4000,https://bj.lianjia.com/zufang/BJ23556994338301...,lj,木樨园
1,芍药居 整租·芍药居北里 2室1厅 东,芍药居北里,6000,https://bj.lianjia.com/zufang/BJ23556927120463...,lj,芍药居
2,定慧寺 整租·恩济庄82号院 1室0厅 北,恩济庄82号院,3500,https://bj.lianjia.com/zufang/BJ23556403944457...,lj,定慧寺
3,通州北苑 整租·长城国际 1室0厅 西,长城国际,3600,https://bj.lianjia.com/zufang/BJ23555436027274...,lj,通州北苑
4,通州北苑 整租·长城国际 2室1厅 东,长城国际,3600,https://bj.lianjia.com/zufang/BJ23555381849953...,lj,通州北苑
5,宋家庄 整租·横三条15号 1室1厅 南,横三条15号,3200,https://bj.lianjia.com/zufang/BJ23563991061480...,lj,宋家庄
6,田村 整租·西木小区 1室1厅 南,西木小区,4400,https://bj.lianjia.com/zufang/BJ23555859873267...,lj,田村
7,顺义其它 整租·中国铁建顺鑫汇 2房间 西,中国铁建顺鑫汇,2300,https://bj.lianjia.com/zufang/BJ23556690390847...,lj,顺义其它
8,甜水园 整租·马道口 1室1厅 南,马道口,4500,https://bj.lianjia.com/zufang/BJ23563796709517...,lj,甜水园
9,学院路 整租·城华园 1室0厅 南,城华园,5500,https://bj.lianjia.com/zufang/BJ23557537414934...,lj,学院路

In [16]:
#总体最低价
min = df['price'].idxmin()
df.iloc[min]

title                              玉泉营 整租·三环新城6号院 0室0厅 南
location                                                 三环新城6号院
price                                                        420
url            https://bj.lianjia.com/zufang/BJ23185835003006...
source                                                        lj
address                                                      玉泉营
price_grade                                                    低
Name: 493, dtype: object

In [17]:
#总体最高价
min = df['price'].idxmax()
df.iloc[min]

title                            整租 | 西城西单四合院精装修院内可停车，办公回所
location                                           西琉璃厂街小区
price                                               350000
url            //bj.ganji.com/zufang/39966369628052x.shtml
source                                                   3
address                                                 整租
price_grade                                              高
Name: 5148, dtype: object

In [18]:
#总体均价
df['price'].mean()

4588.729804646251

In [9]:
#总体描述性统计
df.describe()

               price
count    7576.000000
mean     4588.729805
std      9107.980333
min       420.000000
25%      2500.000000
50%      3500.000000
75%      5200.000000
max    350000.000000

In [10]:
#各区域房源数量
df['address'].value_counts()

整租        1922
单间        1124
西红门        342
亦庄         256
立水桥        140
顺义城        105
定福庄         93
双桥          83
高米店         79
管庄          76
通州北苑        73
朝阳          69
天通苑         63
和义          57
常营          56
清河          56
良乡          50
广安门         48
潘家园         46
垡头          45
西三旗         44
朝青板块        44
北七家         43
石佛营         41
劲松          38
大兴其它        38
旧宫          38
海淀北部新区      37
北苑          37
花乡          36
          ...
广安门内         2
苏州桥          2
知春路          2
广安门外         2
海淀其它         2
西二旗          2
冯村           2
东大桥          1
双榆树          1
海淀           1
金融街          1
南磨房          1
丽泽           1
燕莎           1
三里屯          1
媒体村          1
农业展览馆        1
南苑           1
安定门          1
黄村北          1
魏公村          1
厂洼           1
通州           1
八通轻轨沿线       1
牡丹园          1
大兴开发区        1
怀柔           1
永顺           1
房山其它         1
建国门外         1
Name: address, Length: 241, dtype: int64

In [11]:
#各地区均价和最低价
pvt = pd.pivot_table(df,index=['address'],values=['price'],aggfunc=[np.mean,np.min])
pvt.sort_values(by=('mean','price'))

                 mean   amin
                price  price
address
南口        1880.000000   1800
房山其它      2000.000000   2000
单间        2023.629004    600
温泉        2156.666667   2090
丰台        2170.000000   2150
良乡        2209.200000   1000
长阳        2262.666667   1400
龙泽        2280.000000   2100
城子        2340.000000   2000
八通轻轨沿线    2350.000000   2350
石门营       2366.666667   2300
西门        2400.000000   2400
门头沟其它     2414.285714   2000
阎村        2442.857143   2200
大峪        2445.161290   1800
九棵树       2450.000000   2000
天通苑       2482.380952   2050
花乡        2498.888889   2150
滨河西区      2500.000000   2200
冯村        2500.000000   2400
朝青板块      2501.136364   2190
宣武        2523.333333   2490
新华大街      2566.666667   2100
南磨房       2580.000000   2580
昌平        2580.800000   2090
姚家园       2590.000000   2590
郁花园       2595.000000   2500
大兴周边      2634.652174   2399
通州北苑      2639.712329   2100
天宫院南      2668.750000   1800
...               ...    ...
阜成门       5666.666667   4500
中央别墅区     5675.000000   5200
农展馆       5680.000000   5000
颐和园       5700.000000   5300
朝青        5700.000000   5000
官园        5700.000000   5000
国展        5722.222222   5500
月坛        5725.000000   5300
南沙滩       5750.000000   5000
大山子       5750.000000   5500
知春路       5750.000000   5500
西坝河       5752.941176   4500
石佛营       5786.585366   4800
东直门       5833.333333   5500
白石桥       5840.000000   5500
二里庄       5850.000000   5500
学院路       5859.090909   3700
十里堡       5885.714286   5200
惠新西街      5888.888889   5600
皂君庙       5900.000000   5600
牡丹园       5900.000000   5900
魏公村       5900.000000   5900
安贞        5937.500000   5000
团结湖       6000.000000   5700
厂洼        6000.000000   6000
朝阳门外      6125.000000   6000
双榆树       6200.000000   6200
三里屯       6200.000000   6200
整租        7800.674818    500
怀柔       13000.000000  13000

[241 rows x 2 columns]

In [15]:
#离散化处理
df['price_grade'] = pd.cut(df.price,
                           bins=[0,1500,3000,999999999],
                           labels=['低','中','高']);
df_grp = df['price_grade'].groupby(df["price_grade"]).count()
df_grp

price_grade
低     390
中    2485
高    4701
Name: price_grade, dtype: int64